POST http://localhost:3333/videos
Content-type: application/json  

{
    "title": "Video 01",
    "description": "Esse e o primeiro video",
    "duration": 180
}


###

GET  http://localhost:3333/videos?search=node


###

PUT  http://localhost:3333/videos/e5267a58-4f4c-4260-8472-0e7639a4e1f6
Content-type: application/json  

{
    "title": "Video 02",
    "description": "Esse e o primeiro video",
    "duration": 180
}

###

DELETE  http://localhost:3333/videos/0746504b-2e65-4fc3-b303-3b869cabac4